### ISSUE TITLE
Still working on it ?

### ISSUE THREAD

**Issue by erichard** [zibios/wrike-php-library#1]
Hi @zibios 

I'm trying to integrate Wrike with Gitlab (deep issues integration) and I will use both API for that. As I'm a PHP developper I mainy focus on php libs to use theses API. 

Are you still working on Wrike libs ? Do you consider it usable ?

**Comment by zibios** [comment]
Hi @erichard 
I apologize for the late response. Because there are no requests for the extension of functionality, or error correction, I left the code in its current state. In March I plan to get back to development and release a new version on PHP7 (plus minor updates).
